#define GLAM_VERSION_MAJOR 0
#define GLAM_VERSION_MINOR 2
#define GLAM_VERSION_MICRO 1
#define GLAM_VERSION ((GLAM_VERSION_MAJOR << 24) | (GLAM_VERSION_MINOR << 16) | (GLAM_VERSION_MICRO))

#define HAS_CMATH 1
#define HAS_VARIADIC_TEMPLATES 
#define HAS_STATIC_ASSERT 1
#define HAS_TUPLE 1
